### ISSUE TITLE
Any plans about code updating? 

### ISSUE THREAD

**Issue by sergboec** [pwittchen/EEGReader#1]
Maybe it will be better to move to Android Studio project and replacing ActionBarSherlock.
I'm asking, cause i want to improve csv backup with actual raw signal information, but i can't even build this project

**Comment by pwittchen** [comment]
This project is quite old (more than 3 years). I actually have plans for updating, but I'd rather create a separate library for gathering EEG data in a better way and then write an app using it. I cannot provide you any specific release date because it's my side project. Anyway, you can fork it and improve it if you are in hurry. :-)

**Comment by harimaruthachalam** [comment]
Hi,

Any updates so far in moving to Android Studio?

**Comment by pwittchen** [comment]
I have plans about creating new project basing on this one as I wrote earlier, but I need to find a free time for that. Currently it's my side project.

**Comment by ayushmh** [comment]
I'd like to work with you on this...if it's alright with you....I've free time and you'd get a head start @pwittchen

**Comment by pwittchen** [comment]
Hi, 

Right now, I have quite limited time and this is my side project. When, I'll perform any updates, I'll put them in this repo, so you can watch it if you want to be notified.

Regards,

**Comment by pwittchen** [comment]
Hi @sergboec, @harimaruthachalam, @ayushmh and others!

I just open-sourced brand new [NeuroSky Android SDK](https://github.com/pwittchen/neurosky-android-sdk), which can be used for developing Android projects for NeuroSky MindWave Mobile. I've added sample apps written in Java, RxJava, Kotlin and RxKotlin in the same repo. It uses the latest, modern Android tech stack and you can import and build it easily from Android Studio or CLI.

Check it out at:

https://github.com/pwittchen/neurosky-android-sdk

I'm planning to release it to the Maven Central Repository soon, so you can use it in your projects as a dependency.

Any feedback is appreciated.

Regards,
Piotr
